version: '3.8'
services:
  web:
    build: .
    command: gunicorn logistics.wsgi:application --bind 0.0.0.0 --port ${PORT:-8000}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=logistics.settings
      - PORT=${PORT:-8000}