version: '3.8'
services:
  web:
    build: .
    command: gunicorn logistics.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://logistics_8mza_user:4NbhcetfdPGqa5TJdAyKmCAHjs336IzI@dpg-d1k3n7vdiees73e1kv50-a.oregon-postgres.render.com/logistics_8mza