services:
  - name: logistics
    type: web
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVarGroups:
      - logistics-production  # Reference to environment group created in Render dashboard
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: logistics.settings